version: '3'

# This file is not intended for production usage,
# rather its to simplify the usage of docker compose up,
# as in development environments where this file is present,
# docker will use it and then build its own image from the Dockerfile.

services:
  app:
    image: not-three-local
    build:
      context: .
      dockerfile: Dockerfile
