name: "Bug Report"
description: "Report a problem"
title: "[Bug]: "
labels: [bug]
body:
  - type: dropdown
    id: project
    attributes:
      label: "Which project is this issue related to?"
      options:
        - "@not3/ui"
        - "@not3/api"
        - "@not3/cli"
        - "@not3/sdk"
        - "@not3/draw"
      multiple: false
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Which version are you using?"
      placeholder: "e.g., v1.2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Bug description..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce the issue?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "Expected behavior..."

  - type: textarea
    id: error_stack
    attributes:
      label: "Error stacktrace (if applicable)"
      description: "Paste the error message or stacktrace here."
      render: "shell"

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional context"
      description: "Any other information we should know?"
