name: "Issue Helper"

on:
  issues:
    types: [opened, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          sync-labels: 1
